<?php namespace mlu\groupwise\xsd;
/**
  * XSD-abstracted interfaces...
  */
abstract class domainObjectType extends \mlu\rest\xsd_restriction { 
	const UNMAPPED='UNMAPPED';
	const BASE_GATEWAY='BASE_GATEWAY';
	const BASE_LDAP_SERVER='BASE_LDAP_SERVER';
	const BASE_OBJECT='BASE_OBJECT';
	const ACCESS_CONTROL='ACCESS_CONTROL';
	const ACTION='ACTION';
	const ADMINISTRATOR='ADMINISTRATOR';
	const ADMIN_APP='ADMIN_APP';
	const ADMIN_NOTIFICATION='ADMIN_NOTIFICATION';
	const ADMIN_PREFERENCE='ADMIN_PREFERENCE';
	const APP_EVENT_ASSOCIATION='APP_EVENT_ASSOCIATION';
	const AREA_ACCESS='AREA_ACCESS';
	const CUSTOM_ADDRESS='CUSTOM_ADDRESS';
	const CUSTOM_ADDRESS_ASSOCIATION='CUSTOM_ADDRESS_ASSOCIATION';
	const CUSTOM_PREFERENCE='CUSTOM_PREFERENCE';
	const CUSTOM_RECORD='CUSTOM_RECORD';
	const DIRECTORY='DIRECTORY';
	const DOMAIN='DOMAIN';
	const DOMAIN_LINK='DOMAIN_LINK';
	const EVENT_ACTION_ASSOCIATION='EVENT_ACTION_ASSOCIATION';
	const EXTERNAL_SYSTEM='EXTERNAL_SYSTEM';
	const GATEWAY_ALIAS='GATEWAY_ALIAS';
	const GATEWAY_HOST_ALIAS='GATEWAY_HOST_ALIAS';
	const GATEWAY='GATEWAY';
	const GROUP='GROUP';
	const GROUP_MEMBER='GROUP_MEMBER';
	const CAL_PUB_HOST='CAL_PUB_HOST';
	const DVA='DVA';
	const GWIA='GWIA';
	const INTERNET_DOMAIN='INTERNET_DOMAIN';
	const LDAP_SERVER='LDAP_SERVER';
	const LDAP_SERVER_ASSC='LDAP_SERVER_ASSC';
	const LIBRARY='LIBRARY';
	const LIBRARY_ACCESS_RIGHTS='LIBRARY_ACCESS_RIGHTS';
	const LIBRARY_AREA='LIBRARY_AREA';
	const MTA='MTA';
	const MTA_PROFILE='MTA_PROFILE';
	const MUST_MESSAGE='MUST_MESSAGE';
	const NDS_DS_FIELD_MAP='NDS_DS_FIELD_MAP';
	const NICKNAME='NICKNAME';
	const POA='POA';
	const POST_OFFICE='POST_OFFICE';
	const RESOURCE='RESOURCE';
	const RESTORE_AREA='RESTORE_AREA';
	const SCHEDULED_EVENT='SCHEDULED_EVENT';
	const SOFTWARE_AREA='SOFTWARE_AREA';
	const SYSTEM_RECORD='SYSTEM_RECORD';
	const TIMEZONE='TIMEZONE';
	const TRUSTED_APP='TRUSTED_APP';
	const USER='USER';
	const WEB_ACCESS_AGENT='WEB_ACCESS_AGENT';
	const X400_RECORD='X400_RECORD';
}