<?php
namespace mlu\groupwise\xsd;
/**
  * XSD-abstracted interfaces...
  */
abstract class mimeEncoding extends \mlu\rest\xsd_restriction { 
	const WINDOWS_DEFAULT='WINDOWS_DEFAULT';
	const ISO_DEFAULT='ISO_DEFAULT';
	const UTF8='UTF8';
	const ARABIC_ASMO_708='ARABIC_ASMO_708';
	const ARABIC_DOS='ARABIC_DOS';
	const ARABIC_ISO='ARABIC_ISO';
	const ARABIC_WINDOWS_1256='ARABIC_WINDOWS_1256';
	const BALTIC_ISO='BALTIC_ISO';
	const BALTIC_WINDOWS_1257='BALTIC_WINDOWS_1257';
	const CENTRAL_EURO_DOS='CENTRAL_EURO_DOS';
	const CENTRAL_EURO_ISO='CENTRAL_EURO_ISO';
	const CENTRAL_EURO_WINDOWS_1250='CENTRAL_EURO_WINDOWS_1250';
	const CHINESE_SIMP_GB2312='CHINESE_SIMP_GB2312';
	const CHINESE_SIMP_HZ='CHINESE_SIMP_HZ';
	const CHINESE_TRAD_BIG5='CHINESE_TRAD_BIG5';
	const CYRLLIC_DOS='CYRLLIC_DOS';
	const CYRLLIC_ISO='CYRLLIC_ISO';
	const CYRLLIC_KOI8_R='CYRLLIC_KOI8_R';
	const CYRLLIC_KOI8_U='CYRLLIC_KOI8_U';
	const CYRLLIC_WINDOWS='CYRLLIC_WINDOWS';
	const GREEK_ISO='GREEK_ISO';
	const GREEK_WINDOWS='GREEK_WINDOWS';
	const HEBREW_DOS='HEBREW_DOS';
	const HEBREW_ISO='HEBREW_ISO';
	const HEBREW_ISO_LOGICAL='HEBREW_ISO_LOGICAL';
	const HEBREW_ISO_VISUAL='HEBREW_ISO_VISUAL';
	const HEBREW_WINDOWS_1255='HEBREW_WINDOWS_1255';
	const JAPANESE_EUC='JAPANESE_EUC';
	const JAPANESE_ISO2022_JP='JAPANESE_ISO2022_JP';
	const JAPANESE_SHIFT_JIS='JAPANESE_SHIFT_JIS';
	const KOREAN_ISO='KOREAN_ISO';
	const KOREAN_EUC_KR='KOREAN_EUC_KR';
	const THAI_WINDOWS_874='THAI_WINDOWS_874';
	const TURKISH_ISO='TURKISH_ISO';
	const TURKISH_WINDOWS_1254='TURKISH_WINDOWS_1254';
	const USER_DEFINED='USER_DEFINED';
	const UTF7='UTF7';
	const VIETNAMESE_WINDOWS='VIETNAMESE_WINDOWS';
	const WESTERN_EURO_ISO_8859_1='WESTERN_EURO_ISO_8859_1';
	const WESTERN_EURO_ISO_8859_15='WESTERN_EURO_ISO_8859_15';
	const WESTERN_EURO_WINDOWS_1252='WESTERN_EURO_WINDOWS_1252';
}